export default Object.freeze({
  colors: {
    liberty: '#b7e4cf',
    lightLiberty: '#e3f4ec',
    grey: '#d4d4da',
    navy: '#232444',
    purple: '#575993',
    offWhite: '#f7f7f7',
    red: '#b61b28',
    brightRed: '#ee2c3c',
    white: '#fff',
  },
  fontFamily: {
    sans: "'Ringside Regular A', 'Ringside Regular B', 'Helvetica', sans-serif",
    wide: "'Ringside Wide A', 'Ringside Wide B', 'Helvetica', sans-serif",
    compressed: "'Ringside Compressed A', 'Ringside Compressed B', 'Helvetica', sans-serif",
  },
  fontSize: {
    xs: '12px',
    sm: '14px',
    base: '16px',
    md: '18px',
    lg: '22px',
    xl: '32px',
    '2xl': '42px',
    '3xl': '72px',
  },
  leading: {
    sub: 0.9,
    none: 1,
    tight: 1.25,
    snug: 1.333,
    normal: 1.4,
    relaxed: 1.625,
    loose: 2,
  },
  maxWidth: {
    content: '710px',
    section: '1150px',
    site: '1400px',
  },
  screens: {
    xs: '375px',
    sm: '410px',
    md: '768px',
    lg: '1024px',
    xl: '1440px',
    '2xl': '2560px',
  },
  spacing: {
    sp0: '4px',
    sp1: '8px',
    sp2: '16px',
    sp3: '24px',
    sp4: '32px',
    sp6: '48px',
    sp8: '64px',
  },
});
